#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ostree
Version  : 2018.4
Release  : 19
URL      : https://github.com/ostreedev/ostree/releases/download/v2018.4/libostree-2018.4.tar.xz
Source0  : https://github.com/ostreedev/ostree/releases/download/v2018.4/libostree-2018.4.tar.xz
Summary  : Git for operating system binaries
Group    : Development/Tools
License  : BSD-2-Clause LGPL-2.0 LGPL-2.1
Requires: ostree-bin
Requires: ostree-config
Requires: ostree-data
Requires: ostree-lib
Requires: ostree-doc
BuildRequires : bison
BuildRequires : docbook-xml
BuildRequires : gjs
BuildRequires : gjs-dev
BuildRequires : gpgme-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : libarchive-devel
BuildRequires : libassuan-dev
BuildRequires : libcap-dev
BuildRequires : libgpg-error-dev
BuildRequires : libxslt-bin
BuildRequires : parallel
BuildRequires : pkgconfig(e2p)
BuildRequires : pkgconfig(fuse)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(libcurl)
BuildRequires : pkgconfig(libgsystem)
BuildRequires : pkgconfig(liblzma)
BuildRequires : pkgconfig(libsoup-2.4)
BuildRequires : pkgconfig(libsystemd)
BuildRequires : pkgconfig(zlib)
BuildRequires : util-linux

%description
libostree
---------
New! See the docs online at [Read The Docs (OSTree)](https://ostree.readthedocs.org/en/latest/ )

%package bin
Summary: bin components for the ostree package.
Group: Binaries
Requires: ostree-data
Requires: ostree-config

%description bin
bin components for the ostree package.


%package config
Summary: config components for the ostree package.
Group: Default

%description config
config components for the ostree package.


%package data
Summary: data components for the ostree package.
Group: Data

%description data
data components for the ostree package.


%package dev
Summary: dev components for the ostree package.
Group: Development
Requires: ostree-lib
Requires: ostree-bin
Requires: ostree-data
Provides: ostree-devel

%description dev
dev components for the ostree package.


%package doc
Summary: doc components for the ostree package.
Group: Documentation

%description doc
doc components for the ostree package.


%package lib
Summary: lib components for the ostree package.
Group: Libraries
Requires: ostree-data

%description lib
lib components for the ostree package.


%prep
%setup -q -n libostree-2018.4

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1525215731
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make check ||:

%install
export SOURCE_DATE_EPOCH=1525215731
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)
/usr/lib/ostree/ostree-prepare-root
/usr/lib/ostree/ostree-remount

%files bin
%defattr(-,root,root,-)
/usr/bin/ostree
/usr/bin/rofiles-fuse
/usr/libexec/libostree/grub2-15_ostree
/usr/libexec/libostree/ostree-trivial-httpd

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system-generators/ostree-system-generator
/usr/lib/systemd/system/ostree-prepare-root.service
/usr/lib/systemd/system/ostree-remount.service
/usr/lib/tmpfiles.d/ostree-tmpfiles.conf

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/OSTree-1.0.typelib
/usr/share/bash-completion/completions/ostree
/usr/share/gir-1.0/*.gir
/usr/share/ostree/trusted.gpg.d/README-gpg

%files dev
%defattr(-,root,root,-)
/usr/include/ostree-1/ostree-async-progress.h
/usr/include/ostree-1/ostree-autocleanups.h
/usr/include/ostree-1/ostree-bootconfig-parser.h
/usr/include/ostree-1/ostree-core.h
/usr/include/ostree-1/ostree-deployment.h
/usr/include/ostree-1/ostree-diff.h
/usr/include/ostree-1/ostree-dummy-enumtypes.h
/usr/include/ostree-1/ostree-gpg-verify-result.h
/usr/include/ostree-1/ostree-mutable-tree.h
/usr/include/ostree-1/ostree-repo-deprecated.h
/usr/include/ostree-1/ostree-repo-file.h
/usr/include/ostree-1/ostree-repo.h
/usr/include/ostree-1/ostree-sepolicy.h
/usr/include/ostree-1/ostree-sysroot-upgrader.h
/usr/include/ostree-1/ostree-sysroot.h
/usr/include/ostree-1/ostree-types.h
/usr/include/ostree-1/ostree-version.h
/usr/include/ostree-1/ostree.h
/usr/lib64/libostree-1.so
/usr/lib64/pkgconfig/ostree-1.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
%doc /usr/share/man/man5/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libostree-1.so.1
/usr/lib64/libostree-1.so.1.0.0
